window.ADVENTURE={
  title:"La Coppa dei Quattro Regni",
  totalScenes:100,
  avatars:[
    {id:"leo",label:"Leo",emoji:"🧑🏻‍🦱",style:"maglia blu e mantello argentato"},
    {id:"nico",label:"Nico",emoji:"👦🏽",style:"felpa verde da esploratore e scarpe rosse"},
    {id:"mia",label:"Mia",emoji:"👧🏻",style:"divisa viola e mantello stellato"},
    {id:"luna",label:"Luna",emoji:"👧🏾",style:"giacca dorata da avventuriera e fascia azzurra"}
  ],
  scenes:{
    s001:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Il tiro impossibile",art:"⚽✨",text:"{{name}} è rimasto da solo sul campo dopo l'allenamento. Prova l'ultimo tiro della giornata. Il pallone colpisce il palo, ma invece di tornare indietro attraversa una luce blu comparsa dentro la rete.",choices:[{label:"⚽ Corri dentro la porta luminosa",next:"s002"},{label:"🔎 Guarda prima cosa c'è dietro la rete",next:"s003"}]},
    s002:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Dall'altra parte",art:"🌌🥅",text:"{{name}} attraversa la luce. Lo stadio è ancora lì, ma le tribune galleggiano nel cielo e sopra il prato brillano quattro lune. Il pallone rotola verso una piccola creatura con un cappello da arbitro.",choices:[{label:"👋 Saluta la creatura",next:"s004"},{label:"🏃 Insegui subito il pallone",next:"s005"}]},
    s003:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"La tessera sotto l'erba",art:"🧩🌱",text:"Dietro la porta, {{name}} vede qualcosa luccicare. È una tessera dorata a forma di mattoncino. Appena la raccoglie, sulla tessera compare una parola: COSTRUISCI.",gain:"tessera dorata",choices:[{label:"✨ Tocca la tessera",next:"s006"},{label:"⚽ Attraversa il portale con la tessera",next:"s002"}]},
    s004:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"L'arbitro Folletto",art:"🧙‍♂️🟨",text:"«Finalmente!» esclama il folletto. «La Coppa dei Quattro Regni è stata rubata. Senza di lei, tutte le partite finiranno zero a zero per sempre!» Poi indica tre porte apparse a bordo campo.",choices:[{label:"🚪 Scegli la porta con il fulmine",next:"s007"},{label:"🧱 Scegli la porta fatta di blocchi",next:"s008"}]},
    s005:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Il pallone ribelle",art:"⚽💨",text:"Il pallone accelera da solo. {{name}} lo segue fino alla linea di centrocampo, dove si apre una botola. Dal buco arriva una voce: «Se vuoi il pallone, dimostra di essere coraggioso!»",choices:[{label:"🕳️ Scendi nella botola",next:"s009"},{label:"↩️ Torna dal folletto",next:"s004"}]},
    s006:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Una scala in dieci secondi",art:"🧱🪜",text:"La tessera vibra. Dal terreno spuntano blocchi colorati che si incastrano da soli formando una scala altissima. In cima c'è una bandierina con il simbolo della Coppa.",choices:[{label:"🪜 Sali sulla scala",next:"s010",requires:"tessera dorata"},{label:"⚽ Porta la tessera attraverso il portale",next:"s002"}]},
    s007:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"La porta del fulmine",art:"⚡🚪",text:"La porta si apre su un corridoio pieno di scarpe da calcio sospese in aria. Una sola coppia brilla di luce azzurra. Sotto c'è scritto: SOLO PER CHI OSA.",choices:[{label:"👟 Indossa le scarpe luminose",next:"s011"},{label:"🚪 Torna alle tre porte",next:"s004"}]},
    s008:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Il regno dei blocchi",art:"🧱🏰",text:"Oltre la porta si estende una città costruita con milioni di blocchi. Al centro, una torre sta crollando pezzo dopo pezzo. Una bambina con un mantello rosso grida: «Aiutami a salvarla!»",choices:[{label:"🏗️ Aiuta a ricostruire la torre",next:"s012"},{label:"👀 Cerca il simbolo della Coppa",next:"s013"}]},
    s009:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Sotto il campo",art:"🕯️🐉",text:"Sotto lo stadio c'è una galleria illuminata da cristalli. In fondo dorme un piccolo drago con il pallone stretto tra le zampe. Non sembra cattivo. Sta russando fortissimo.",choices:[{label:"🤫 Avvicinati piano",next:"s014"},{label:"🎵 Prova a svegliarlo cantando",next:"s015"}]},
    s010:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"La mappa dei quattro regni",art:"🗺️✨",text:"In cima alla scala {{name}} trova una mappa: Regno dei Blocchi, Foresta degli Stregoni, Castello della Squadra Ombra e Arena delle Quattro Lune. Al centro lampeggia una X.",gain:"mappa dei regni",choices:[{label:"🗺️ Porta la mappa al folletto",next:"s004"},{label:"🌙 Segui subito la X",next:"s016"}]},
    s011:{chapter:"Capitolo 1",kicker:"Lo stadio incantato",title:"Le scarpe del vento",art:"👟🌪️",text:"Appena {{name}} allaccia le scarpe, fa tre passi e attraversa mezzo campo come un razzo. Sul tallone compare il simbolo di una luna. Le scarpe sembrano conoscere la strada.",gain:"scarpe del vento",choices:[{label:"🌪️ Lasciati guidare dalle scarpe",next:"s016"},{label:"🧙 Torna dal folletto",next:"s004"}]},
    s012:{chapter:"Capitolo 1",kicker:"Il regno dei blocchi",title:"La torre salvata",art:"🏰⭐",text:"{{name}} trova il pezzo mancante e lo incastra appena in tempo. La torre smette di tremare. La bambina consegna una chiave fatta di quattro blocchi colorati: «Ti servirà al Castello Ombra.»",gain:"chiave a blocchi",choices:[{label:"🔑 Prendi la strada del castello",next:"s016"},{label:"🔎 Esplora ancora la città",next:"s013"}]},
    s013:{chapter:"Capitolo 1",kicker:"Il regno dei blocchi",title:"Il simbolo nascosto",art:"🔍🧱",text:"Tra le case {{name}} trova un muro con lo stesso simbolo della Coppa. Una fila di blocchi forma una freccia verso una bottega chiusa. Dall'interno arriva un tintinnio.",choices:[{label:"🚪 Bussa alla bottega",next:"s017"},{label:"🏰 Torna ad aiutare la torre",next:"s012"}]},
    s014:{chapter:"Capitolo 1",kicker:"Sotto lo stadio",title:"Il drago portiere",art:"🐉🥅",text:"Il drago apre un occhio. «Questo pallone è mio», borbotta. Poi indica due pietre come pali. «Segnami un gol e te lo restituisco.»",choices:[{label:"⚽ Tira forte nell'angolino",next:"s018"},{label:"🎩 Prova un tiro con effetto magico",next:"s019"}]},
    s015:{chapter:"Capitolo 1",kicker:"Sotto lo stadio",title:"Una canzone terribile",art:"🎤🐉",text:"{{name}} canta così forte che il drago si sveglia di colpo... e scoppia a ridere. «La canzone più brutta che abbia mai sentito! Mi sei simpatico. Giochiamo?»",choices:[{label:"⚽ Accetta la sfida",next:"s014"},{label:"🤝 Chiedigli aiuto per la Coppa",next:"s020"}]},
    s016:{chapter:"Capitolo 2",kicker:"Verso i quattro regni",title:"La strada si divide",art:"🛤️🌠",text:"La prima parte della missione è compiuta. Davanti a {{name}} si aprono tre strade: una fatta di blocchi, una avvolta dalla nebbia viola e una coperta di bandiere nere. La vera avventura comincia adesso.",choices:[{label:"🧱 Regno dei Blocchi",next:"s008"},{label:"🔮 Foresta degli Stregoni — presto",next:"s021"}]},
    s017:{chapter:"Capitolo 1",kicker:"Il regno dei blocchi",title:"Il costruttore misterioso",art:"🛠️🧙",text:"La porta si apre. Un vecchio costruttore mostra a {{name}} un frammento argentato. «È caduto dalla Coppa. Posso dartelo, ma prima devi promettere di usarlo per aiutare qualcuno.»",gain:"frammento della coppa",choices:[{label:"🤝 Prometti e prendi il frammento",next:"s016"},{label:"🏰 Prima aiuta la città",next:"s012"}]},
    s018:{chapter:"Capitolo 1",kicker:"Sotto lo stadio",title:"Gol!",art:"🥅🔥",text:"Il tiro parte velocissimo. Il drago vola verso il pallone, ma arriva un istante troppo tardi. «GOL!» ruggisce felice. Restituisce il pallone a {{name}} e gli regala una piccola scaglia luminosa.",gain:"scaglia di drago",choices:[{label:"✨ Chiedi cosa fa la scaglia",next:"s020"},{label:"⬆️ Torna allo stadio",next:"s004"}]},
    s019:{chapter:"Capitolo 1",kicker:"Sotto lo stadio",title:"Il tiro a mezzaluna",art:"🌙⚽",text:"{{name}} colpisce il pallone di lato. La palla curva intorno al drago e finisce tra i pali. Per un secondo lascia dietro di sé una scia di stelle. Il drago applaude con le ali.",gain:"scaglia di drago",choices:[{label:"🐉 Parla con il drago",next:"s020"},{label:"⬆️ Torna allo stadio",next:"s004"}]},
    s020:{chapter:"Capitolo 1",kicker:"Sotto lo stadio",title:"Il segreto del drago",art:"🐉🔮",text:"«La Coppa non è stata rubata per vincere una partita», sussurra il drago. «Qualcuno vuole aprire la Porta delle Quattro Lune. Cerca i frammenti prima della Squadra Ombra.»",choices:[{label:"🌠 Parti verso i regni",next:"s016"},{label:"🧙 Avvisa prima il folletto",next:"s004"}]},
    s021:{chapter:"Capitolo 2",kicker:"Foresta degli Stregoni",title:"Continua presto…",art:"🌲🔮",text:"Tra gli alberi viola qualcosa si muove. Una luce verde disegna nell'aria il simbolo della Coppa. Questa è la fine del primo prototipo: il motore è pronto per continuare fino a 100 scene.",choices:[{label:"↺ Ricomincia il prototipo",next:"s001"},{label:"🧱 Torna al bivio",next:"s016"}]}
  }
};