window.ADVENTURE=(()=>{
const avatars=[
{id:'leo',label:'Leo',emoji:'🧑🏻‍🦱',style:'capelli scuri ricci, maglia da calcio blu, mantello argentato'},
{id:'nico',label:'Nico',emoji:'👦🏽',style:'capelli corti scuri, felpa verde da esploratore, scarpe rosse'},
{id:'mia',label:'Mia',emoji:'👧🏻',style:'capelli castani, divisa sportiva viola, mantello stellato'},
{id:'luna',label:'Luna',emoji:'👧🏾',style:'capelli ricci scuri, giacca dorata da avventuriera, fascia azzurra'}];
const chapters=[
['Capitolo 1','Lo Stadio Incantato'],['Capitolo 2','Il Regno dei Blocchi'],['Capitolo 3','La Foresta degli Stregoni'],['Capitolo 4','Il Castello della Squadra Ombra'],['Capitolo 5',"L'Arena delle Quattro Lune"]];
const arts=[
['⚽✨','🌌🥅','🧩🌱','🧙‍♂️🟨','⚽💨','🧱🪜','⚡🚪','🧱🏰','🕯️🐉','🗺️✨','👟🌪️','🏰⭐','🔍🧱','🐉🥅','🎤🐉','🛤️🌠','🛠️🧙','🥅🔥','🌙⚽','🐉🔮'],
['🧱🌄','🏘️🧱','🌉🧩','🛠️👧','🗼⚙️','🚂🧱','🕳️🔧','🧰✨','🏟️🧱','🧙‍♂️🔩','🌋🧱','🚪🔐','🪜🌟','🏰🧩','🐦🔶','⚽🧱','🤖🛡️','🧭🧱','💎🏗️','🚪🌲'],
['🌲🔮','🍄✨','🦉📜','🌫️🧙','🌳👁️','🪄⚽','🐺🌙','🧪💚','🗝️🍃','🌉🌫️','🧙‍♀️⭐','🌀🌲','🔥🧪','🐸👑','🌙🪵','🪞✨','🦌🔔','⚽🌿','💜🔮','🏰🌑'],
['🏰🌑','🚩⚫','🕵️‍♂️🗝️','🛡️👤','🕯️🧱','🗺️🏰','🚪👂','⚽🖤','🧤🌑','🪤⚙️','🦇📜','🗝️🌘','🏟️🌑','👑⚫','🧱🚪','⚔️✨','🌉🏰','🔓💎','🏃🌙','🚪🌌'],
['🌌🏟️','🌕🌗','👥✨','🏆🔒','⚽🌠','🧙‍♂️🌙','🐉🔥','🧱🛡️','🌲💫','⚫⚽','🥅🌌','🪄⭐','💥🏟️','🤝✨','🏆🌙','🚪💫','🎉⚽','👑🏆','🌅🏟️','⭐🏆']];
const data=[
['Il tiro impossibile',"{{name}} resta sul campo dopo l'allenamento. Un ultimo tiro colpisce il palo e attraversa una luce blu comparsa nella rete."],
["Dall'altra parte",'Lo stadio è lo stesso, ma le tribune galleggiano nel cielo e quattro lune brillano sopra il prato.'],
['La tessera dorata','Dietro la porta {{name}} trova un mattoncino dorato. Sopra compare una parola: COSTRUISCI.'],
['L’arbitro Folletto','Un folletto con il fischietto spiega che la Coppa dei Quattro Regni è scomparsa e che qualcuno vuole aprire la Porta delle Quattro Lune.'],
['Il pallone ribelle','Il pallone corre da solo verso il centrocampo e sparisce in una botola.'],
['La scala di blocchi','La tessera dorata richiama blocchi colorati che costruiscono una scala verso una bandierina luminosa.'],
['Le scarpe del vento','In un corridoio sospeso, una coppia di scarpe azzurre vibra come se conoscesse la strada.'],
['La città di blocchi','Una porta conduce a una città costruita con blocchi. Una torre sta crollando pezzo dopo pezzo.'],
['Il drago portiere','Sotto lo stadio dorme un piccolo drago con il pallone stretto tra le zampe.'],
['La mappa dei regni','In cima alla scala c’è una mappa con quattro luoghi e una X che lampeggia.'],
['La corsa del vento','Le scarpe trascinano {{name}} verso un arco di pietra che pulsa di luce.'],
['La torre salvata','{{name}} trova il pezzo mancante e salva la torre. In premio riceve una chiave fatta di quattro blocchi.'],
['La bottega chiusa','Un simbolo della Coppa conduce a una bottega da cui arriva un tintinnio misterioso.'],
['La sfida del drago','Il drago propone una sfida: segnare un gol tra due cristalli per riavere il pallone.'],
['La canzone terribile','Una canzone stonata sveglia il drago, che invece di arrabbiarsi scoppia a ridere.'],
['Il primo bivio','Tre strade conducono al Regno dei Blocchi, alla Foresta degli Stregoni e al Castello Ombra.'],
['Il costruttore misterioso','Un vecchio costruttore mostra un frammento argentato della Coppa e chiede una promessa: usarlo per aiutare qualcuno.'],
['Gol al drago','Il tiro entra nell’angolino. Il drago applaude e regala a {{name}} una scaglia luminosa.'],
['Il tiro a mezzaluna','Il pallone curva lasciando una scia di stelle e sorprende il drago.'],
['Il segreto del drago','Il drago rivela che i frammenti della Coppa devono essere trovati prima della Squadra Ombra.'],
['La strada a incastro','La strada cambia forma sotto i piedi di {{name}}. Ogni blocco sembra aspettare il pezzo giusto.'],
['La piazza senza ponte','Nella piazza tutti sono fermi: il ponte che unisce le due metà della città è sparito.'],
['Il ponte spezzato','Tre grandi pezzi galleggiano sopra il fiume. Bisogna capire in quale ordine montarli.'],
['Ada la costruttrice','Ada, giovane costruttrice col mantello rosso, chiede aiuto per trovare il progetto rubato.'],
['La torre degli ingranaggi','Una torre piena di ruote gira troppo velocemente e rischia di smontare tutta la città.'],
['Il treno di mattoni','Un trenino di blocchi parte senza conducente verso le montagne di mattoni.'],
['La galleria segreta','Sotto i binari c’è una galleria con il simbolo della Squadra Ombra.'],
['La cassetta degli attrezzi','Una cassetta si apre solo davanti a chi ha aiutato davvero qualcuno nel regno.'],
['Lo stadio smontato','Lo stadio del regno è stato smontato. La finale locale non può iniziare.'],
['Il Mastro delle Ruote','Il Mastro delle Ruote sa chi ha preso il frammento, ma vuole vedere un gesto di coraggio.'],
['Il vulcano di blocchi','Dal vulcano cadono blocchi roventi che stanno chiudendo l’unica strada verso il castello.'],
['La porta a quattro colori','La porta ha quattro serrature colorate e nessuna maniglia.'],
['La scala invisibile','Una scala appare soltanto quando {{name}} mette insieme i simboli trovati lungo il cammino.'],
['Il castello capovolto','Nel castello tutto è al contrario: pavimento sul soffitto e porte sotto i tavoli.'],
['Il corvo arancione','Un corvo arancione ha rubato una chiave e la porta in cima a una gru.'],
['La partita dei costruttori','Per vincere informazioni bisogna giocare una breve partita contro i costruttori del regno.'],
['Il guardiano meccanico','Un enorme guardiano di metallo blocca il passaggio e chiede la parola d’ordine.'],
['La bussola quadrata','Una bussola fatta di quattro quadrati indica una porta nascosta nel muro.'],
['Il cuore della città','Nel cuore della città pulsa un frammento della Coppa, protetto da una gabbia di blocchi.'],
['Verso la foresta','Con il frammento al sicuro, un sentiero di blocchi verdi conduce {{name}} verso la foresta viola.'],
['Gli alberi viola','Gli alberi viola si spostano quando {{name}} non li guarda. Il sentiero cambia continuamente.'],
['Il sentiero dei funghi','Funghi luminosi formano parole sul terreno. Una sola fila sembra indicare la direzione giusta.'],
['Il gufo bibliotecario','Un gufo con piccoli occhiali custodisce un libro che racconta la storia della Coppa.'],
['La nebbia che parla','La nebbia sussurra due indicazioni diverse. Una voce sembra amichevole, l’altra troppo sicura.'],
['L’albero con un occhio','Un albero apre un enorme occhio dorato e domanda cosa {{name}} sta cercando davvero.'],
['Il pallone incantato','Un pallone verde vola tra i rami e ogni rimbalzo trasforma una foglia in una stella.'],
['Il lupo della luna','Un lupo argentato appare sul sentiero. Non ringhia: porta al collo il simbolo di una luna.'],
['La pozione verde','Una piccola strega sta preparando una pozione per vedere le tracce invisibili della Squadra Ombra.'],
['La chiave di foglie','Tra le radici cresce una chiave fatta di foglie che non si lascia raccogliere facilmente.'],
['Il ponte nella nebbia','Un ponte compare e scompare nella nebbia. Bisogna scegliere il momento giusto per attraversare.'],
['La strega delle stelle','La Strega delle Stelle conosce un incantesimo capace di proteggere un frammento della Coppa.'],
['Il vortice degli alberi','Un vortice solleva foglie e rami. Nel centro brilla una porta di luce.'],
['La prova del fuoco freddo','Una fiamma azzurra non brucia, ma congela tutto ciò che tocca.'],
['Il principe ranocchio','Un ranocchio con una corona sostiene di essere il principe della foresta e vuole essere accompagnato a casa.'],
['La radura della luna','Nella radura, la luna disegna sul terreno lo stesso simbolo visto sulla Coppa.'],
['Lo specchio bugiardo','Uno specchio mostra tre versioni di {{name}}, ma soltanto una copia i movimenti correttamente.'],
['Il cervo dei campanelli','Un cervo con piccoli campanelli d’argento guida {{name}} verso un sentiero nascosto.'],
['La partita delle radici','Radici giganti formano due porte da calcio. Per passare serve segnare senza danneggiare gli alberi.'],
['Il secondo frammento','Dentro un tronco antico riposa il secondo frammento della Coppa, avvolto da luce viola.'],
['La strada nera','Appena il frammento viene preso, una strada nera compare tra gli alberi e conduce al Castello Ombra.'],
['Il castello nero','Il Castello Ombra sorge sopra una collina nera, ma una finestra in cima lampeggia come una stella.'],
['Le bandiere senza vento','Le bandiere nere restano immobili anche se soffia un vento fortissimo. Dietro una di esse c’è un passaggio.'],
['La chiave nascosta','In una nicchia {{name}} trova una serratura identica alla chiave del Regno dei Blocchi.'],
['Il cavaliere d’ombra','Un cavaliere fatto di fumo blocca la scala e chiede perché {{name}} vuole la Coppa.'],
['Il corridoio delle candele','Centinaia di candele si accendono una alla volta indicando due corridoi diversi.'],
['La mappa del castello','Su un tavolo c’è la mappa del castello con una stanza cancellata con inchiostro nero.'],
['La porta che ascolta','Una porta senza maniglia si apre soltanto se sente la risposta giusta a un indovinello.'],
['Il campo proibito','Nel cortile nascosto c’è un campo da calcio dove nessuno ha il permesso di giocare.'],
['Il portiere senza volto','Un portiere d’ombra para ogni tiro prima ancora che il pallone venga calciato.'],
['La sala delle trappole','La sala successiva è piena di fili, botole e leve. Qualcuno vuole rallentare {{name}}.'],
['Il messaggio dei pipistrelli','Tre pipistrelli portano pezzetti di un messaggio strappato.'],
['La chiave della mezzaluna','Una chiave a forma di mezzaluna pende sopra un pozzo senza fondo.'],
['Lo stadio sotterraneo','Sotto il castello si trova uno stadio segreto pieno di spettatori silenziosi.'],
['Il Capitano Ombra','Il Capitano Ombra appare. Dice di aver rubato i frammenti per impedire a qualcun altro di usarli.'],
['Il muro di blocchi','Un muro di blocchi separa {{name}} dalla sala della Coppa.'],
['Il duello di luce','Una sfera di luce e una sfera d’ombra si scontrano sopra il campo. Bisogna scegliere da che parte stare.'],
['Il ponte levatoio','Il ponte levatoio comincia a salire mentre la Squadra Ombra arriva alle spalle.'],
['Il terzo frammento','In una stanza rotonda brilla il terzo frammento della Coppa.'],
['La fuga sul tetto','Con il frammento in mano, {{name}} corre sui tetti mentre il castello si riempie di luce lunare.'],
['La porta delle lune','Una porta con quattro lune incise si apre verso l’Arena finale.'],
['L’Arena delle Quattro Lune','L’Arena galleggia nello spazio. Quattro lune illuminano un campo grande come una città.'],
['Le lune si allineano','Le quattro lune cominciano ad allinearsi e la Porta delle Lune vibra dietro una delle porte da calcio.'],
['Gli alleati arrivano','Ada, il gufo, il drago e altri amici incontrati lungo il viaggio arrivano per aiutare {{name}}.'],
['La Coppa chiusa','I tre frammenti si avvicinano, ma la Coppa resta chiusa: manca una scintilla di coraggio.'],
['Il primo calcio stellare','Un pallone fatto di stelle cade dal cielo e si ferma davanti a {{name}}.'],
['Il Folletto ritorna','Il Folletto arbitro ricompare e ammette di non aver raccontato tutta la verità.'],
['Il drago in picchiata','Il piccolo drago vola sopra il campo e respinge una nube d’ombra diretta verso gli spalti.'],
['La difesa di blocchi','I costruttori montano in pochi secondi una barriera di blocchi per proteggere la Coppa.'],
['L’incantesimo della foresta','La Strega delle Stelle lancia un incantesimo che rende visibili le vere intenzioni di tutti.'],
['La Squadra Ombra in campo','La Squadra Ombra entra in campo. Il Capitano propone di decidere tutto con una partita.'],
['La porta delle stelle','Dietro la porta compare un vortice pieno di stelle. Se si apre del tutto, i regni potrebbero separarsi per sempre.'],
['Il tiro impossibile','{{name}} deve provare il tiro più difficile dell’avventura, usando ciò che ha imparato nei quattro regni.'],
['Il cielo si spezza','Il pallone colpisce la luce e il cielo sembra spezzarsi in quattro colori.'],
['La scelta del capitano','Tutti guardano {{name}}: salvare subito la Coppa o aiutare prima qualcuno rimasto in pericolo.'],
['La Coppa ricomposta','I tre frammenti finalmente si uniscono. La Coppa torna intera e illumina tutta l’Arena.'],
['La porta si richiude','La Porta delle Quattro Lune comincia a chiudersi, ma dall’altra parte arriva una voce misteriosa.'],
['La partita più strana del mondo','Prima di tornare a casa, amici e avversari giocano insieme la partita più strana e felice del mondo.'],
['Il vero vincitore','Non conta chi segna più gol: il pubblico applaude chi ha aiutato gli altri durante l’avventura.'],
['Ritorno allo stadio','Una luce blu riporta {{name}} nello stadio di casa. Sul prato c’è ancora il pallone del primo tiro.'],
['La nuova leggenda','Da quel giorno, ogni volta che quattro stelle compaiono sopra lo stadio, {{name}} sa che da qualche parte una nuova avventura sta per cominciare.']];
const labels=[['⚽ Vai avanti','🔎 Esplora un’altra strada'],['🧱 Costruisci una soluzione','🧭 Cerca un passaggio diverso'],['✨ Segui la magia','🌲 Guarda meglio intorno'],['🗝️ Entra con cautela','⚽ Prova la via più coraggiosa'],['🌙 Continua verso la Coppa','🤝 Aiuta prima gli amici']];
const gains={3:'tessera dorata',10:'mappa dei regni',12:'chiave a blocchi',18:'scaglia di drago',20:'frammento argentato',28:'attrezzi magici',39:'primo frammento',49:'chiave di foglie',59:'secondo frammento',72:'chiave mezzaluna',78:'terzo frammento',95:'coppa ricomposta'};
const reqs={26:'tessera dorata',32:'chiave a blocchi',38:'attrezzi magici',47:'scaglia di drago',58:'chiave di foglie',63:'chiave a blocchi',72:'mappa dei regni',78:'chiave mezzaluna',84:'frammento argentato',94:'terzo frammento'};
const scenes={};
data.forEach(([title,text],i)=>{const n=i+1,c=Math.floor(i/20),end=(c+1)*20,next=n<100?n+1:1,alt=n+2<=end?n+2:next;let choices=n===100?[{label:'⭐ Ricomincia una nuova avventura',next:'s001'},{label:'🏆 Rivedi il finale',next:'s095'}]:[{label:labels[c][0],next:`s${String(next).padStart(3,'0')}`},{label:labels[c][1],next:`s${String(alt).padStart(3,'0')}`}];if([20,40,60,80].includes(n))choices=[{label:'🌟 Continua al prossimo regno',next:`s${String(n+1).padStart(3,'0')}`},{label:'🧭 Ripassa l’ultimo indizio',next:`s${String(n-2).padStart(3,'0')}`}];if(reqs[n])choices[0].requires=reqs[n];scenes[`s${String(n).padStart(3,'0')}`]={chapter:chapters[c][0],kicker:chapters[c][1],title,art:arts[c][i%20],image:`assets/scenes/s${String(n).padStart(3,'0')}.webp`,imagePrompt:`Children's illustrated adventure book, original fantasy world, ${chapters[c][1].toLowerCase()}, scene: ${title.toLowerCase()}, football, magic, colorful building blocks, cinematic but friendly, expressive characters, no text, landscape 4:3, consistent protagonist avatar`,text,choices,...(gains[n]?{gain:gains[n]}:{})};});
return{title:'La Coppa dei Quattro Regni',totalScenes:100,avatars,scenes};
})();